services:

  node-docker:
    image: selenium/node-docker:4
    volumes:
      - assets:/opt/selenium/assets
      - downloads:/home/seluser/Downloads
      - $PWD/${gwen.initDir}${slash}conf/browsers/grid.toml:/opt/selenium/docker.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_DOCKER_CONFIG_FILENAME=docker.toml
      - SE_START_VNC=true
      - TZ
    shm_size: 2gb

  selenium-hub:
    image: selenium/hub:4
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  gwen:
    depends_on:
      - node-docker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GWEN_ENV
      - GWEN_PROFILE
      - GWEN_BROWSER
      - GWEN_DRY_RUN
      - GWEN_PARALLEL
      - GWEN_THREADS
      - GWEN_HEADLESS
      - GWEN_VIDEO
      - GWEN_WEB_VERSION
      - SELENIUM_HUB
      - NO_COLOR
      - TZ
    volumes:
      - $PWD:/project
      - assets:/home/gwen/.assets
      - downloads:/home/gwen/Downloads
    working_dir: /project
    command: bash -c "yarn install && yarn gwen -b -c ${gwen.initDir}${slash}conf/browsers/grid.conf ${gwen.initDir}${slash}features"

  gwen-dry-run:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GWEN_ENV
      - GWEN_WEB_VERSION
      - NO_COLOR
      - TZ
    volumes:
      - "$PWD:/project"
    working_dir: /project
    command: bash -c "yarn install && yarn gwen -bn --parallel ${gwen.initDir}${slash}features"

volumes:
  assets: 
  downloads:
