services:
  chrome:
    image: selenoid/chrome:latest
    networks:
      - gwen-net
  edge:
    image: browsers/edge:latest
    networks:
      - gwen-net
  firefox:
    image: selenoid/firefox:latest
    networks:
      - gwen-net
  video-recorder:
    image: selenoid/video-recorder:latest-release
    networks:
      - gwen-net
  selenoid:
    image: aerokube/selenoid:latest-release
    networks:
      - gwen-net
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/${gwen.initDir}${slash}browsers:/etc/selenoid/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/${gwen.initDir}${slash}output/.video:/opt/selenoid/video"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/${gwen.initDir}${slash}output/.video
    command: ["-container-network", "gwen-net", "-video-output-dir", "/opt/selenoid/video"]
  selenoid-ui:
    depends_on:
      - selenoid
      - $GWEN_BROWSER
    image: aerokube/selenoid-ui:latest
    environment:
      - GWEN_BROWSER
    networks:
      - gwen-net
    ports: 
      - "8999:8999"
    command: ["--selenoid-uri", "http://selenoid:4444", "--listen", ":8999"]
  gwen:
    depends_on:
      - selenoid
      - video-recorder
      - $GWEN_BROWSER
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SELENIUM_HUB
      - NO_COLOR
      - GWEN_ENV
      - GWEN_PROCESS
      - GWEN_BROWSER
      - GWEN_DRY_RUN
      - GWEN_PARALLEL
      - GWEN_THREADS
      - GWEN_HEADLESS
      - GWEN_VIDEO
      - GWEN_WEB_VERSION
    volumes:
      - "$PWD:/project"
    working_dir: /project
    command: bash -c "yarn install && yarn gwen -b -c gwen/conf/browsers/selenoid.conf gwen/features"
    networks:
      - gwen-net
  gwen-dry-run:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NO_COLOR
      - GWEN_WEB_VERSION
    volumes:
      - "$PWD:/project"
    working_dir: /project
    command: bash -c "yarn install && yarn gwen -bn --parallel gwen/features"
    networks:
      - gwen-net
networks:
  gwen-net:
    name: gwen-net
