name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: gwen-web
    - name: Checkout Gwen core repo
      uses: actions/checkout@v2
      with:
        repository: gwen-interpreter/gwen
        path: gwen
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
        cache: sbt
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    - uses: sbt/setup-sbt@v1
    - name: Build and Test
      working-directory: ./gwen-web
      run: sbt -v -Dfile.encoding=UTF-8 -Dgwen.web.browser.headless=true +test
